### PR TITLE
TRITON-1943 add Jenkinsfiles to Triton repositories

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by cburroughs** [comment]
Testing out those ACLs.

**Comment by trentm** [comment]
> Testing out those ACLs.

Indeed it did not build this. However, it also didn't create a joyent-org/job/sdc-sapi job from which I can quickly/easily do a build.  I've restarted a joyent-org org scan to see if it picks it up. I'll leave this PR alive until I have a chance to play with that.

**Comment by trentm** [comment]
> 21:44:57 GitHub API Usage: Current quota has 3676 remaining (323 over budget). Next quota of 5000 in 59 min. Sleeping for 5 min 35 sec.

Oh boy, this is going to take a while.

**Comment by trentm** [comment]
Well, it got there for sdc-sapi, but:

```
  Checking pull-requests...

    Checking pull request #8
    (not from a trusted source)
      ‘Jenkinsfile’ not found
    Does not meet criteria
```

Hrm. I guess that "Jenkinsfile not found" is because "(not from a trusted source)".  I guess if "automatic creation of the PR jenkins job from outside contributors" doesn't work for repos for which we don't already have such a job, isn't the end of the world.

**Comment by trentm** [comment]
Screenshot 2019-10-24 16 25 21

✅

**Comment by cburroughs** [comment]
>  I guess if "automatic creation of the PR jenkins job from outside contributors" doesn't work for repos for which we don't already have such a job, isn't the end of the world.

ah, I guess that's a consequence of the "trusted Jenkinsfiles" model.  It doesn't trust changes, or creation.  Which apart from the confusing use of the word "trust" sounds reasonably consistent.

**Pull request merged**
